# Generated by Django 4.0.3 on 2022-04-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=500, null=True)),
                ('cat_description', models.TextField(blank=True, max_length=500, null=True)),
                ('cat_thumb', models.ImageField(blank=True, null=True, upload_to='static/images/category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('product_thumb', models.ImageField(blank=True, null=True, upload_to='static/images/product')),
                ('product_description', models.TextField(blank=True, null=True)),
                ('unit_in_stock', models.IntegerField(null=True)),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
