# Generated by Django 4.0.3 on 2022-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_cat_thumb_alter_product_product_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
