# Generated by Django 4.0.3 on 2022-04-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_clothes_customer_laptop_order_paymentmethod_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
