# Generated by Django 4.0.3 on 2022-04-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
