# Generated by Django 4.0.3 on 2022-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_laptop_product_ptr_remove_phone_product_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='isPublished',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
