# Generated by Django 4.0.3 on 2022-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Red', 'Red'), ('Gray', 'Gray'), ('Blue', 'Blue'), ('White', 'White'), ('Pink', 'Pink')], default='Black', max_length=200, null=True),
        ),
    ]
