# Generated by Django 4.0.3 on 2022-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_author_phone_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
