# Generated by Django 4.0.3 on 2022-05-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_shippingaddress_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='district',
        ),
    ]
